"""Initial schema

Revision ID: 54d6a56ce6a5
Revises: None
Create Date: 2026-06-10 11:34:49.719784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d6a56ce6a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('disease_id', sa.String(length=50), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('icd_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_index('idx_diseases_category', 'diseases', ['category'], unique=False)
    op.create_index(op.f('ix_diseases_category'), 'diseases', ['category'], unique=False)
    op.create_index(op.f('ix_diseases_disease_name'), 'diseases', ['disease_name'], unique=False)
    op.create_table('genes',
    sa.Column('gene_id', sa.String(length=50), nullable=False),
    sa.Column('gene_symbol', sa.String(length=50), nullable=False),
    sa.Column('gene_name', sa.String(length=255), nullable=False),
    sa.Column('chromosome', sa.String(length=10), nullable=False),
    sa.Column('function', sa.String(length=255), nullable=False),
    sa.Column('protein', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('gene_id')
    )
    op.create_index('idx_genes_chromosome', 'genes', ['chromosome'], unique=False)
    op.create_index('idx_genes_function', 'genes', ['function'], unique=False)
    op.create_index(op.f('ix_genes_chromosome'), 'genes', ['chromosome'], unique=False)
    op.create_index(op.f('ix_genes_function'), 'genes', ['function'], unique=False)
    op.create_index(op.f('ix_genes_gene_symbol'), 'genes', ['gene_symbol'], unique=True)
    op.create_table('pathways',
    sa.Column('pathway_id', sa.String(length=50), nullable=False),
    sa.Column('pathway_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pathway_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('disease_gene_associations',
    sa.Column('association_id', sa.String(length=50), nullable=False),
    sa.Column('gene_id', sa.String(length=50), nullable=False),
    sa.Column('disease_id', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.gene_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('association_id'),
    sa.UniqueConstraint('gene_id', 'disease_id', name='uq_gene_disease')
    )
    op.create_index('idx_assoc_score_level', 'disease_gene_associations', ['confidence_score', 'evidence_level'], unique=False)
    op.create_index(op.f('ix_disease_gene_associations_confidence_score'), 'disease_gene_associations', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_disease_gene_associations_disease_id'), 'disease_gene_associations', ['disease_id'], unique=False)
    op.create_index(op.f('ix_disease_gene_associations_gene_id'), 'disease_gene_associations', ['gene_id'], unique=False)
    op.create_table('favorite_diseases',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'disease_id')
    )
    op.create_table('favorite_genes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.gene_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'gene_id')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('variant_id', sa.String(length=50), nullable=False),
    sa.Column('gene_id', sa.String(length=50), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('mutation_type', sa.String(length=100), nullable=False),
    sa.Column('clinical_significance', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.gene_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index('idx_variants_gene_sig', 'variants', ['gene_id', 'clinical_significance'], unique=False)
    op.create_index(op.f('ix_variants_clinical_significance'), 'variants', ['clinical_significance'], unique=False)
    op.create_index(op.f('ix_variants_gene_id'), 'variants', ['gene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_gene_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_clinical_significance'), table_name='variants')
    op.drop_index('idx_variants_gene_sig', table_name='variants')
    op.drop_table('variants')
    op.drop_table('saved_searches')
    op.drop_table('favorite_genes')
    op.drop_table('favorite_diseases')
    op.drop_index(op.f('ix_disease_gene_associations_gene_id'), table_name='disease_gene_associations')
    op.drop_index(op.f('ix_disease_gene_associations_disease_id'), table_name='disease_gene_associations')
    op.drop_index(op.f('ix_disease_gene_associations_confidence_score'), table_name='disease_gene_associations')
    op.drop_index('idx_assoc_score_level', table_name='disease_gene_associations')
    op.drop_table('disease_gene_associations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('pathways')
    op.drop_index(op.f('ix_genes_gene_symbol'), table_name='genes')
    op.drop_index(op.f('ix_genes_function'), table_name='genes')
    op.drop_index(op.f('ix_genes_chromosome'), table_name='genes')
    op.drop_index('idx_genes_function', table_name='genes')
    op.drop_index('idx_genes_chromosome', table_name='genes')
    op.drop_table('genes')
    op.drop_index(op.f('ix_diseases_disease_name'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_category'), table_name='diseases')
    op.drop_index('idx_diseases_category', table_name='diseases')
    op.drop_table('diseases')
    # ### end Alembic commands ###
